In [1]:
from numpy import asarray
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import UpSampling2D,Input

In [2]:
X = asarray([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [3]:
X = X.reshape((1, X.shape[0], X.shape[1], 1))

In [4]:
print(X)

[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]

  [[7]
   [8]
   [9]]]]


In [5]:
X.shape

(1, 3, 3, 1)

In [6]:
model = Sequential()
model.add(Input(shape=(X.shape[1], X.shape[2], 1)))
model.add(UpSampling2D(size = (2,2)))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d (UpSampling2D) (None, 6, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


2022-12-26 22:27:04.294077: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-12-26 22:27:04.301656: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-12-26 22:27:04.302242: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-12-26 22:27:04.303140: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

In [7]:
upsampled_X = model.predict(X)

2022-12-26 22:27:07.163635: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


In [9]:
upsampled_X_ = upsampled_X.reshape((upsampled_X.shape[1],upsampled_X.shape[2]))
print(upsampled_X_)

[[1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]
 [4. 4. 5. 5. 6. 6.]
 [4. 4. 5. 5. 6. 6.]
 [7. 7. 8. 8. 9. 9.]
 [7. 7. 8. 8. 9. 9.]]


In [11]:
from tensorflow.keras.layers import Conv2DTranspose, Input

# define simple 3x3 input for this exercise
X = asarray([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [12]:
X = X.reshape((1, X.shape[0], X.shape[1], 1))

In [13]:
print(X)

[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]

  [[7]
   [8]
   [9]]]]


In [42]:

model1 = Sequential()
model1.add(Input(shape=(X.shape[1], X.shape[2], 1)))
model1.add(Conv2DTranspose(1, (2,2), strides=(3,3), kernel_initializer='ones'))
model1.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_12 (Conv2DT (None, 9, 9, 1)           5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [43]:
# Apply the model to our input data
transposed_X = model1.predict(X)
transposed_X = transposed_X.reshape((transposed_X.shape[1],transposed_X.shape[2]))
print(transposed_X)

[[1. 1. 0. 2. 2. 0. 3. 3. 0.]
 [1. 1. 0. 2. 2. 0. 3. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 0. 5. 5. 0. 6. 6. 0.]
 [4. 4. 0. 5. 5. 0. 6. 6. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [7. 7. 0. 8. 8. 0. 9. 9. 0.]
 [7. 7. 0. 8. 8. 0. 9. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [44]:
transposed_X.shape

(9, 9)